"""Write a Markdown summary of the reproduced results.

The report is assembled from the CSV tables in ``results/tables`` and links
to the PNG figures in ``results/figures``, so it always agrees with them.

Usage::

    python -m src.analysis.report --tables-dir results/tables \
        --figures-dir results/figures --out results/report/summary.md
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path

import pandas as pd

from src.log import setup_logging

log = logging.getLogger(__name__)

FIGURES = [
    ("label_distribution", "Class balance of the two labelled splits."),
    ("sentence_lengths", "Words per sentence; validation sentences are full sentences, "
                         "training examples include short phrases."),
    ("model_comparison", "Accuracy with 95% Wilson interval, training compute (FLOPs), model size."),
    ("training_curves", "Training loss by optimisation step; validation accuracy and loss by epoch."),
    ("confusion_matrices", "Confusion matrices of the best checkpoint of each model."),
    ("accuracy_vs_size", "Accuracy (95% interval) against number of parameters."),
]


def markdown_table(frame: pd.DataFrame) -> str:
    """Render ``frame`` as a GitHub-flavoured Markdown table."""
    def cell(value) -> str:
        return "" if pd.isna(value) else str(value).replace("|", "\\|")

    lines = [
        "| " + " | ".join(map(str, frame.columns)) + " |",
        "|" + "---|" * len(frame.columns),
    ]
    lines += ["| " + " | ".join(cell(v) for v in row) + " |" for row in frame.itertuples(index=False)]
    return "\n".join(lines)


def headline(comparison: pd.DataFrame, pairwise: pd.DataFrame) -> list[str]:
    """Return bullet points stating the main findings in words."""
    ranked = comparison.sort_values("val_accuracy", ascending=False)
    best, runner_up = ranked.iloc[0], ranked.iloc[1]
    lines = [
        f"- **{best['model']}** has the highest validation accuracy: "
        f"{100 * best['val_accuracy']:.1f}% ({best['correct']}/{best['n_validation']}; "
        f"95% CI {100 * best['val_accuracy_ci95_low']:.1f}-{100 * best['val_accuracy_ci95_high']:.1f}%), "
        f"followed by " + ", ".join(
            f"{row['model']} {100 * row['val_accuracy']:.1f}%" for _, row in ranked.iloc[1:].iterrows()
        ) + "."
    ]
    top_two = {best["model"], runner_up["model"]}
    pair = pairwise.loc[
        pairwise.apply(lambda row: {row["model_a"], row["model_b"]} == top_two, axis=1)
    ]
    if len(pair) == 1:
        p = pair.iloc[0]["mcnemar_exact_p"]
        verdict = "is not" if p >= 0.05 else "is"
        lines.append(
            f"- The {best['model']}-{runner_up['model']} difference "
            f"({100 * (best['val_accuracy'] - runner_up['val_accuracy']):.1f} points) {verdict} "
            f"statistically significant on 872 paired sentences (McNemar exact p = {p:.2f})."
        )
    smallest = comparison.sort_values("parameters_millions").iloc[0]
    lines.append(
        f"- {smallest['model']} is the smallest model ({smallest['parameters_millions']:.0f}M "
        f"parameters) and trails the best by "
        f"{100 * (best['val_accuracy'] - smallest['val_accuracy']):.1f} points."
    )
    return lines


def build_report(tables_dir: Path, figures_dir: Path, out: Path,
                 artifacts: str = "artifacts") -> str:
    """Assemble the Markdown report from the tables and figures.

    ``artifacts`` names the directory the tables were built from, so that a
    report on retrained models (``make rebuild``) says so.
    """
    committed = Path(artifacts) == Path("artifacts")
    read = lambda name: pd.read_csv(tables_dir / f"{name}.csv")  # noqa: E731
    comparison = read("model_comparison")
    pairwise = read("pairwise_comparison")
    original = read("original_report_comparison")
    mismatches = original.loc[~original["matches"]].drop(columns="matches")
    errors = read("misclassified_examples")
    figure_dir = os.path.relpath(figures_dir, out.parent)

    sections = [
        "# Reproduced results: BERT, DistilBERT and RoBERTa on SST-2",
        f"_Generated by `make` from the artifacts in `{artifacts}/`; do not edit by hand._",
        "## Main findings",
        "\n".join(headline(comparison, pairwise)),
        "## Data",
        markdown_table(read("dataset_summary")),
        "## Model comparison",
        markdown_table(comparison),
        "`train_time_hours_recorded` is the wall clock recorded by the original run and "
        "`epoch_minutes_recorded` splits it by epoch using the checkpoint save times. "
        "Both include idle time (the laptop sleeping), so they are records, not results; "
        "`train_pflops` is the hardware-independent cost.",
        "## Validation accuracy and loss by epoch",
        markdown_table(read("per_epoch_validation")),
        "## Classification metrics (best checkpoint, positive class)",
        markdown_table(read("classification_metrics")),
        "## Paired comparison of models (McNemar's exact test)",
        markdown_table(pairwise),
        "## Caveats",
        "\n".join([
            "- The best epoch of each model was chosen on the same 872 validation "
            "sentences that score it, so the best-epoch accuracies are slightly optimistic.",
            "- SST-2's test labels are hidden, so there is no held-out test score.",
            "- These numbers are exact for the committed artifacts. Retraining "
            "(`make rebuild`) gives slightly different numbers: the original run did not "
            "seed the classification head, and GPU/MPS training is not bit-for-bit repeatable."
            if committed else
            f"- These numbers come from the models retrained into `{artifacts}/`. They "
            "differ slightly from the committed artifacts: the original run did not seed "
            "the classification head, and GPU/MPS training is not bit-for-bit repeatable.",
        ]),
        "## Figures",
        "\n\n".join(
            f"**{name.replace('_', ' ').capitalize()}.** {caption}\n\n"
            f"![{name}]({figure_dir}/{name}.png)"
            for name, caption in FIGURES
        ),
        "## Differences from the original report",
        (
            f"Of the {len(original)} numbers in the original report's Tables I and II and "
            f"its confusion matrix, {len(original) - len(mismatches)} are reproduced exactly. "
            "The others are listed below; docs/discrepancies.md explains each one."
        ),
        markdown_table(mismatches),
        "## Most confident errors of the best model",
        markdown_table(errors.head(10)),
    ]
    return "\n\n".join(sections) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Write the Markdown report."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--tables-dir", type=Path, required=True)
    parser.add_argument("--figures-dir", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--artifacts", default="artifacts",
                        help="artifact directory the tables were built from (for the text)")
    args = parser.parse_args(argv)
    setup_logging()
    text = build_report(args.tables_dir, args.figures_dir, args.out, args.artifacts)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    log.info("wrote %s", args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
